/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_AbstractVipsImage */

#ifndef _Included_com_criteo_vips_AbstractVipsImage
#define _Included_com_criteo_vips_AbstractVipsImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    initFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_initFieldIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    abs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_abs
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    add
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_add
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    analyzeLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/AnalyzeLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_analyzeLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    autorot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_autorot
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    avg
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_criteo_vips_AbstractVipsImage_avg
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    bandbool
 * Signature: (Lcom/criteo/vips/enums/VipsOperationBoolean;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_bandbool
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    bandfold
 * Signature: (Lcom/criteo/vips/options/BandfoldOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_bandfold
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    bandjoinConst
 * Signature: (Lcom/criteo/vips/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_bandjoinConst
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    bandmean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_bandmean
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    bandunfold
 * Signature: (Lcom/criteo/vips/options/BandunfoldOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_bandunfold
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    black
 * Signature: (IILcom/criteo/vips/options/BlackOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_black
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    booleanOp
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsOperationBoolean;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_booleanOp
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    booleanConst
 * Signature: (Lcom/criteo/vips/enums/VipsOperationBoolean;Lcom/criteo/vips/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_booleanConst
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    buildlut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_buildlut
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    byteswap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_byteswap
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    cache
 * Signature: (Lcom/criteo/vips/options/CacheOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_cache
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    canny
 * Signature: (Lcom/criteo/vips/options/CannyOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_canny
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    cast
 * Signature: (Lcom/criteo/vips/enums/VipsBandFormat;Lcom/criteo/vips/options/CastOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_cast
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    cMC2LCh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_cMC2LCh
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    cmyk2xyz
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_cmyk2xyz
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    colourspace
 * Signature: (Lcom/criteo/vips/enums/VipsInterpretation;Lcom/criteo/vips/options/ColourspaceOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_colourspace
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    compass
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/CompassOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_compass
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    complex
 * Signature: (Lcom/criteo/vips/enums/VipsOperationComplex;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_complex
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    complex2
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsOperationComplex2;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_complex2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    complexform
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_complexform
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    complexget
 * Signature: (Lcom/criteo/vips/enums/VipsOperationComplexget;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_complexget
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    composite2
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsBlendMode;Lcom/criteo/vips/options/Composite2Options;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_composite2
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    conv
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/ConvOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_conv
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    conva
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/ConvaOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_conva
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    convasep
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/ConvasepOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_convasep
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    convf
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_convf
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    convi
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_convi
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    convsep
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/ConvsepOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_convsep
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    copy
 * Signature: (Lcom/criteo/vips/options/CopyOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_copy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    countlines
 * Signature: (Lcom/criteo/vips/enums/VipsDirection;)D
 */
JNIEXPORT jdouble JNICALL Java_com_criteo_vips_AbstractVipsImage_countlines
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    csvLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/CSVLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_csvLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    csvSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/CSVSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_csvSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    dE00
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_dE00
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    dE76
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_dE76
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    dECMC
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_dECMC
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    deviate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_criteo_vips_AbstractVipsImage_deviate
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    divide
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_divide
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    drawCircle
 * Signature: (Lcom/criteo/vips/PixelPacket;IIILcom/criteo/vips/options/DrawCircleOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_drawCircle
  (JNIEnv *, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    drawImage
 * Signature: (Lcom/criteo/vips/VipsImage;IILcom/criteo/vips/options/DrawImageOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_drawImage
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    drawLine
 * Signature: (Lcom/criteo/vips/PixelPacket;IIII)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_drawLine
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    drawMask
 * Signature: (Lcom/criteo/vips/PixelPacket;Lcom/criteo/vips/VipsImage;II)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_drawMask
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    drawRect
 * Signature: (Lcom/criteo/vips/PixelPacket;IIIILcom/criteo/vips/options/DrawRectOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_drawRect
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    drawSmudge
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_drawSmudge
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    dzSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/DZSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_dzSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    dzSaveBuffer
 * Signature: (Lcom/criteo/vips/options/DZSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_dzSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    embed
 * Signature: (IIIILcom/criteo/vips/options/EmbedOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_embed
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    extractArea
 * Signature: (IIII)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_extractArea
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    extractBand
 * Signature: (ILcom/criteo/vips/options/ExtractBandOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_extractBand
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    eye
 * Signature: (IILcom/criteo/vips/options/EyeOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_eye
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    falsecolour
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_falsecolour
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    fastcor
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_fastcor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    fillNearest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_fillNearest
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    fitsLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/FITSLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_fitsLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    fitsSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/FITSSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_fitsSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    flatten
 * Signature: (Lcom/criteo/vips/options/FlattenOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_flatten
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    flip
 * Signature: (Lcom/criteo/vips/enums/VipsDirection;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_flip
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    float2rad
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_float2rad
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    fractsurf
 * Signature: (IID)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_fractsurf
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    freqmult
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_freqmult
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    fwfft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_fwfft
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gamma
 * Signature: (Lcom/criteo/vips/options/GammaOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_gamma
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gaussblur
 * Signature: (DLcom/criteo/vips/options/GaussblurOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_gaussblur
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gaussmat
 * Signature: (DDLcom/criteo/vips/options/GaussmatOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_gaussmat
  (JNIEnv *, jclass, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gaussnoise
 * Signature: (IILcom/criteo/vips/options/GaussnoiseOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_gaussnoise
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    getpoint
 * Signature: (II)Lcom/criteo/vips/PixelPacket;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_getpoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gifLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/GIFLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_gifLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gifLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/GIFLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_gifLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gifSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/GIFSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_gifSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gifSaveBuffer
 * Signature: (Lcom/criteo/vips/options/GIFSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_gifSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    globalbalance
 * Signature: (Lcom/criteo/vips/options/GlobalbalanceOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_globalbalance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    gravity
 * Signature: (Lcom/criteo/vips/enums/VipsCompassDirection;IILcom/criteo/vips/options/GravityOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_gravity
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    grey
 * Signature: (IILcom/criteo/vips/options/GreyOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_grey
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    grid
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_grid
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    heifLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/HEIFLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_heifLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    heifLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/HEIFLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_heifLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    heifSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/HEIFSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_heifSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    heifSaveBuffer
 * Signature: (Lcom/criteo/vips/options/HEIFSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_heifSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histCum
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histCum
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histEntropy
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_criteo_vips_AbstractVipsImage_histEntropy
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histEqual
 * Signature: (Lcom/criteo/vips/options/HistEqualOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histFind
 * Signature: (Lcom/criteo/vips/options/HistFindOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histFind
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histFindIndexed
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/HistFindIndexedOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histFindIndexed
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histFindNdim
 * Signature: (Lcom/criteo/vips/options/HistFindNdimOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histFindNdim
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histLocal
 * Signature: (IILcom/criteo/vips/options/HistLocalOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histLocal
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histMatch
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histMatch
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histNorm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histNorm
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    histPlot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_histPlot
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    houghCircle
 * Signature: (Lcom/criteo/vips/options/HoughCircleOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_houghCircle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    houghLine
 * Signature: (Lcom/criteo/vips/options/HoughLineOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_houghLine
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    hSV2sRGB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_hSV2sRGB
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    iccExport
 * Signature: (Lcom/criteo/vips/options/ICCExportOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_iccExport
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    iccImport
 * Signature: (Lcom/criteo/vips/options/ICCImportOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_iccImport
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    iccTransform
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/ICCTransformOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_iccTransform
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    identity
 * Signature: (Lcom/criteo/vips/options/IdentityOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_identity
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    ifthenelse
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/IfthenelseOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_ifthenelse
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    insert
 * Signature: (Lcom/criteo/vips/VipsImage;IILcom/criteo/vips/options/InsertOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_insert
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    invert
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_invert
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    invertlut
 * Signature: (Lcom/criteo/vips/options/InvertLUTOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_invertlut
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    invfft
 * Signature: (Lcom/criteo/vips/options/InvFFTOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_invfft
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    join
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsDirection;Lcom/criteo/vips/options/JoinOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_join
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jp2kLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/JP2KLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_jp2kLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jp2kLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/JP2KLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_jp2kLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jp2kSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/JP2KSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_jp2kSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jp2kSaveBuffer
 * Signature: (Lcom/criteo/vips/options/JP2KSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_jp2kSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jpegLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/JPEGLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_jpegLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jpegLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/JPEGLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_jpegLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jpegSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/JPEGSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_jpegSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jpegSaveBuffer
 * Signature: (Lcom/criteo/vips/options/JPEGSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_jpegSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jpegSaveMime
 * Signature: (Lcom/criteo/vips/options/JPEGSaveMimeOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_jpegSaveMime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jxlLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/JXLLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_jxlLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jxlLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/JXLLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_jxlLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jxlSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/JXLSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_jxlSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    jxlSaveBuffer
 * Signature: (Lcom/criteo/vips/options/JXLSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_jxlSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    lab2LabQ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_lab2LabQ
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    lab2LabS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_lab2LabS
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    lab2LCh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_lab2LCh
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    lab2XYZ
 * Signature: (Lcom/criteo/vips/options/Lab2XYZOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_lab2XYZ
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    labelregions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_labelregions
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    labQ2Lab
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_labQ2Lab
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    labQ2LabS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_labQ2LabS
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    labQ2sRGB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_labQ2sRGB
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    labS2Lab
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_labS2Lab
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    labS2LabQ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_labS2LabQ
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    lCh2CMC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_lCh2CMC
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    lCh2Lab
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_lCh2Lab
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    linear
 * Signature: (Lcom/criteo/vips/PixelPacket;Lcom/criteo/vips/PixelPacket;Lcom/criteo/vips/options/LinearOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_linear
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    linecache
 * Signature: (Lcom/criteo/vips/options/LinecacheOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_linecache
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    logmat
 * Signature: (DDLcom/criteo/vips/options/LogmatOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_logmat
  (JNIEnv *, jclass, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    magickLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/MagickLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_magickLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    magickLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/MagickLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_magickLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    magickSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/MagickSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_magickSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    magickSaveBuffer
 * Signature: (Lcom/criteo/vips/options/MagickSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_magickSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maplut
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/options/MapLUTOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_maplut
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskButterworth
 * Signature: (IIDDDLcom/criteo/vips/options/MaskButterworthOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskButterworth
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskButterworthBand
 * Signature: (IIDDDDDLcom/criteo/vips/options/MaskButterworthBandOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskButterworthBand
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskButterworthRing
 * Signature: (IIDDDDLcom/criteo/vips/options/MaskButterworthRingOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskButterworthRing
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskFractal
 * Signature: (IIDLcom/criteo/vips/options/MaskFractalOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskFractal
  (JNIEnv *, jclass, jint, jint, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskGaussian
 * Signature: (IIDDLcom/criteo/vips/options/MaskGaussianOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskGaussian
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskGaussianBand
 * Signature: (IIDDDDLcom/criteo/vips/options/MaskGaussianBandOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskGaussianBand
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskGaussianRing
 * Signature: (IIDDDLcom/criteo/vips/options/MaskGaussianRingOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskGaussianRing
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskIdeal
 * Signature: (IIDLcom/criteo/vips/options/MaskIdealOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskIdeal
  (JNIEnv *, jclass, jint, jint, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskIdealBand
 * Signature: (IIDDDLcom/criteo/vips/options/MaskIdealBandOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskIdealBand
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    maskIdealRing
 * Signature: (IIDDLcom/criteo/vips/options/MaskIdealRingOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_maskIdealRing
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    math
 * Signature: (Lcom/criteo/vips/enums/VipsOperationMath;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_math
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    math2
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsOperationMath2;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_math2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    math2Const
 * Signature: (Lcom/criteo/vips/enums/VipsOperationMath2;Lcom/criteo/vips/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_math2Const
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    matLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/MatLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_matLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    matrixinvert
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_matrixinvert
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    matrixLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/MatrixLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_matrixLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    matrixprint
 * Signature: (Lcom/criteo/vips/options/MatrixprintOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_matrixprint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    matrixSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/MatrixSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_matrixSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    max
 * Signature: (Lcom/criteo/vips/options/MaxOptions;)D
 */
JNIEXPORT jdouble JNICALL Java_com_criteo_vips_AbstractVipsImage_max
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    measure
 * Signature: (IILcom/criteo/vips/options/MeasureOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_measure
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    merge
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsDirection;IILcom/criteo/vips/options/MergeOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_merge
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    min
 * Signature: (Lcom/criteo/vips/options/MinOptions;)D
 */
JNIEXPORT jdouble JNICALL Java_com_criteo_vips_AbstractVipsImage_min
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    morph
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsOperationMorphology;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_morph
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    mosaic
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsDirection;IIIILcom/criteo/vips/options/MosaicOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_mosaic
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    msb
 * Signature: (Lcom/criteo/vips/options/MsbOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_msb
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    multiply
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_multiply
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    openexrLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/OpenexrLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_openexrLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    openslideLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/OpenslideLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_openslideLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    pdfLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/PDFLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_pdfLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    pdfLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/PDFLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_pdfLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    percent
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_AbstractVipsImage_percent
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    perlin
 * Signature: (IILcom/criteo/vips/options/PerlinOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_perlin
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    phasecor
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_phasecor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    pngLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/PNGLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_pngLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    pngLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/PNGLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_pngLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    pngSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/PNGSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_pngSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    pngSaveBuffer
 * Signature: (Lcom/criteo/vips/options/PNGSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_pngSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    ppmLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/PPMLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_ppmLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    ppmSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/PPMSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_ppmSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    premultiply
 * Signature: (Lcom/criteo/vips/options/PremultiplyOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_premultiply
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    profile
 * Signature: ()Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_profile
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    profileLoad
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_profileLoad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    project
 * Signature: ()Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_project
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    rad2float
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_rad2float
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    radLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/RadLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_radLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    radLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/RadLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_radLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    radSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/RadSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_radSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    radSaveBuffer
 * Signature: (Lcom/criteo/vips/options/RadSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_radSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    rank
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_rank
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    rawLoad
 * Signature: (Ljava/lang/String;IIILcom/criteo/vips/options/RawLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_rawLoad
  (JNIEnv *, jclass, jstring, jint, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    rawSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/RawSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_rawSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    rawSaveFd
 * Signature: (ILcom/criteo/vips/options/RawSaveFdOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_rawSaveFd
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    recomb
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_recomb
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    reduce
 * Signature: (DDLcom/criteo/vips/options/ReduceOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_reduce
  (JNIEnv *, jobject, jdouble, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    reduceh
 * Signature: (DLcom/criteo/vips/options/ReducehOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_reduceh
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    reducev
 * Signature: (DLcom/criteo/vips/options/ReducevOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_reducev
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    relational
 * Signature: (Lcom/criteo/vips/VipsImage;Lcom/criteo/vips/enums/VipsOperationRelational;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_relational
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    relationalConst
 * Signature: (Lcom/criteo/vips/enums/VipsOperationRelational;Lcom/criteo/vips/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_relationalConst
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    remainder
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_remainder
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    remainderConst
 * Signature: (Lcom/criteo/vips/PixelPacket;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_remainderConst
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    replicate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_replicate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    resize
 * Signature: (DLcom/criteo/vips/options/ResizeOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_resize
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    rot
 * Signature: (Lcom/criteo/vips/enums/VipsAngle;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_rot
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    rot45
 * Signature: (Lcom/criteo/vips/options/Rot45Options;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_rot45
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    round
 * Signature: (Lcom/criteo/vips/enums/VipsOperationRound;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_round
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    scale
 * Signature: (Lcom/criteo/vips/options/ScaleOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_scale
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    scRGB2BW
 * Signature: (Lcom/criteo/vips/options/ScRGB2BWOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_scRGB2BW
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    scRGB2sRGB
 * Signature: (Lcom/criteo/vips/options/ScRGB2sRGBOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_scRGB2sRGB
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    scRGB2XYZ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_scRGB2XYZ
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    sequential
 * Signature: (Lcom/criteo/vips/options/SequentialOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_sequential
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    sharpen
 * Signature: (Lcom/criteo/vips/options/SharpenOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_sharpen
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    shrink
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_shrink
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    shrinkh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_shrinkh
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    shrinkv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_shrinkv
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    sign
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_sign
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    sines
 * Signature: (IILcom/criteo/vips/options/SinesOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_sines
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    smartcrop
 * Signature: (IILcom/criteo/vips/options/SmartcropOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_smartcrop
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    sobel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_sobel
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    spcor
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_spcor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    spectrum
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_spectrum
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    sRGB2HSV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_sRGB2HSV
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    sRGB2scRGB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_sRGB2scRGB
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    stats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_stats
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    stdif
 * Signature: (IILcom/criteo/vips/options/StdifOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_stdif
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    subsample
 * Signature: (IILcom/criteo/vips/options/SubsampleOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_subsample
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    subtract
 * Signature: (Lcom/criteo/vips/VipsImage;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_subtract
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    svgLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/SvgLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_svgLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    svgLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/SvgLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_svgLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    text
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/TextOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_text
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    thumbnail
 * Signature: (Ljava/lang/String;ILcom/criteo/vips/options/ThumbnailOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_thumbnail
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    thumbnailBuffer
 * Signature: ([BILcom/criteo/vips/options/ThumbnailBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_thumbnailBuffer
  (JNIEnv *, jclass, jbyteArray, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    thumbnailImage
 * Signature: (ILcom/criteo/vips/options/ThumbnailImageOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_thumbnailImage
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    tiffLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/TIFFLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_tiffLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    tiffLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/TIFFLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_tiffLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    tiffSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/TIFFSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_tiffSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    tiffSaveBuffer
 * Signature: (Lcom/criteo/vips/options/TIFFSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_tiffSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    tilecache
 * Signature: (Lcom/criteo/vips/options/TilecacheOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_tilecache
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    tonelut
 * Signature: (Lcom/criteo/vips/options/ToneLUTOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_tonelut
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    transpose3d
 * Signature: (Lcom/criteo/vips/options/Transpose3dOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_transpose3d
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    unpremultiply
 * Signature: (Lcom/criteo/vips/options/UnpremultiplyOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_unpremultiply
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    vipsLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/VipsLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_vipsLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    vipsSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/VipsSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_vipsSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    webpLoad
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/WebpLoadOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_webpLoad
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    webpLoadBuffer
 * Signature: ([BLcom/criteo/vips/options/WebpLoadBufferOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_webpLoadBuffer
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    webpSave
 * Signature: (Ljava/lang/String;Lcom/criteo/vips/options/WebpSaveOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_webpSave
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    webpSaveBuffer
 * Signature: (Lcom/criteo/vips/options/WebpSaveBufferOptions;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_AbstractVipsImage_webpSaveBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    worley
 * Signature: (IILcom/criteo/vips/options/WorleyOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_worley
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    wrap
 * Signature: (Lcom/criteo/vips/options/WrapOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_wrap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    xyz
 * Signature: (IILcom/criteo/vips/options/XYZOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_xyz
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    xyz2cmyk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_xyz2cmyk
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    xYZ2Lab
 * Signature: (Lcom/criteo/vips/options/XYZ2LabOptions;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_xYZ2Lab
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    xYZ2scRGB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_xYZ2scRGB
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    xYZ2Yxy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_xYZ2Yxy
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    yxy2XYZ
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_yxy2XYZ
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    zone
 * Signature: (IILcom/criteo/vips/options/ZoneOptions;)Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_AbstractVipsImage_zone
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_criteo_vips_AbstractVipsImage
 * Method:    zoom
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_AbstractVipsImage_zoom
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
