/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_criteo_vips_VipsImage */

#ifndef _Included_com_criteo_vips_VipsImage
#define _Included_com_criteo_vips_VipsImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    initFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_initFieldIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    newFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_newFromByteBuffer__Ljava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    newFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_newFromByteBuffer__Ljava_nio_ByteBuffer_2ILjava_lang_String_2
  (JNIEnv *, jobject, jobject, jint, jstring);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    newFromBuffer
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_newFromBuffer___3BI
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    newFromBuffer
 * Signature: ([BILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_newFromBuffer___3BILjava_lang_String_2
  (JNIEnv *, jobject, jbyteArray, jint, jstring);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    newFromFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_newFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    newFromImageNative
 * Signature: (Lcom/criteo/vips/Image;[D)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_newFromImageNative
  (JNIEnv *, jobject, jobject, jdoubleArray);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    imageGetFormatNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsImage_imageGetFormatNative
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    imageGetInterpretationNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsImage_imageGetInterpretationNative
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    max1Native
 * Signature: (Lcom/criteo/vips/Max1Result;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_max1Native
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    writeToArrayNative
 * Signature: (Ljava/lang/String;IZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_criteo_vips_VipsImage_writeToArrayNative
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    writeToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_writeToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    writeToFileNative
 * Signature: (Ljava/lang/String;Z[DI)V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_writeToFileNative
  (JNIEnv *, jobject, jstring, jboolean, jdoubleArray, jint);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsImage_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsImage_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    getBands
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsImage_getBands
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    getPointPixelPacketNative
 * Signature: (II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_criteo_vips_VipsImage_getPointPixelPacketNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    hasAlpha
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_criteo_vips_VipsImage_hasAlpha
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    applyConvertTosRGB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_applyConvertTosRGB
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    getNbFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_criteo_vips_VipsImage_getNbFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    applyRemoveAutorotAngle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_applyRemoveAutorotAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    clone
 * Signature: ()Lcom/criteo/vips/VipsImage;
 */
JNIEXPORT jobject JNICALL Java_com_criteo_vips_VipsImage_clone
  (JNIEnv *, jobject);

/*
 * Class:     com_criteo_vips_VipsImage
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_criteo_vips_VipsImage_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
